<template>
    <svg
        viewBox="0 0 32 32"
        xmlns="http://www.w3.org/2000/svg"
    >
        <circle
            cx="9"
            cy="23"
            r="5"
        />
        <circle
            cx="23"
            cy="9"
            r="5"
        />
        <circle
            cx="24"
            cy="24"
            r="3"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
        />
        <path
            d="M12.5 19.5 18.5 13.5M13.5 13.5h5v5"
            fill="none"
            stroke="currentColor"
            stroke-width="2.5"
            stroke-linecap="round"
            stroke-linejoin="round"
        />
    </svg>
</template>
